# This file was generated by GoReleaser. DO NOT EDIT.
cask "junto" do
  version "1.3.0"

  on_macos do
    sha256 "9d22be1d5be85008146580980df7ac14a9b496db2694c58d5bd828310c5dc45c"
    url "https://github.com/swayam-mishra/junto/releases/download/v#{version}/junto_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "189ae32cecdc60da750a96ad3f1f4f3a36ac1c02bb4dd44f6389c1b92c54eca7"
      url "https://github.com/swayam-mishra/junto/releases/download/v#{version}/junto_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d77ca98571514805f19c2667b4c6462385780a2d9dd5bcdea4d60d7a008a4679"
      url "https://github.com/swayam-mishra/junto/releases/download/v#{version}/junto_#{version}_linux_arm64.tar.gz"
    end
  end

  name "junto"
  desc "Watch media in sync with friends — no server, no account"
  homepage "https://github.com/swayam-mishra/junto"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
    ]

  binary "junto"

  # No zap stanza required

  caveats <<~EOS
    Host a watch party:   junto create movie.mkv
    Join one:             junto join <roomcode>
  EOS
end
