# This file was generated by GoReleaser. DO NOT EDIT.
cask "junto" do
  version "1.4.0"

  on_macos do
    sha256 "1aa5b8c154b0edafa93e8c102852a6dfca6a0634f79543a0a894adf8263f6c2c"
    url "https://github.com/swayam-mishra/junto/releases/download/v#{version}/junto_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "21cb9103b8029be11f43fde50b5e6e57498500be8be1ff9251163b70a0e62dda"
      url "https://github.com/swayam-mishra/junto/releases/download/v#{version}/junto_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2f44bb5be8da2834287d19a73750df4080a7b8174647575ffbab2d0e032e617d"
      url "https://github.com/swayam-mishra/junto/releases/download/v#{version}/junto_#{version}_linux_arm64.tar.gz"
    end
  end

  name "junto"
  desc "Watch media in sync with friends — no server, no account"
  homepage "https://github.com/swayam-mishra/junto"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
    ]

  binary "junto"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h", "#{staged_path}/junto"], print_stderr: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/junto"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Host a watch party:   junto create movie.mkv
    Join one:             junto join <roomcode>
  EOS
end
