# This file was generated by GoReleaser. DO NOT EDIT.
cask "junto" do
  version "1.3.1"

  on_macos do
    sha256 "687d4c604e2c84b10d42c11a2962c56df0fc22106ac02df8fd715861eee7f607"
    url "https://github.com/swayam-mishra/junto/releases/download/v#{version}/junto_#{version}_darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "d2d387a020b5057a219ed833ff97783ac395aa3cd4a07ceb9d30912d9a0907d6"
      url "https://github.com/swayam-mishra/junto/releases/download/v#{version}/junto_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "710c49c426aaa034ce6202b821bf17c1e0d7d91713bb055326bca3ad15d608c8"
      url "https://github.com/swayam-mishra/junto/releases/download/v#{version}/junto_#{version}_linux_arm64.tar.gz"
    end
  end

  name "junto"
  desc "Watch media in sync with friends — no server, no account"
  homepage "https://github.com/swayam-mishra/junto"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
    ]

  binary "junto"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h", "#{staged_path}/junto"], print_stderr: false).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/junto"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Host a watch party:   junto create movie.mkv
    Join one:             junto join <roomcode>
  EOS
end
