# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Junto < Formula
  desc "Watch media in sync with friends — no server, no account"
  homepage "https://github.com/swayam-mishra/junto"
  version "1.2.0"
  license "MIT"

  depends_on "mpv"

  on_macos do
    url "https://github.com/swayam-mishra/junto/releases/download/v1.2.0/junto_1.2.0_darwin_all.tar.gz"
    sha256 "d650774027f410736e90cb1f5ac8583cd26b9f0b2bcf36ef639c01c03518082b"

    define_method(:install) do
      bin.install "junto"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swayam-mishra/junto/releases/download/v1.2.0/junto_1.2.0_linux_amd64.tar.gz"
      sha256 "00e8334b3b32a6dc8f3aff78198cb8673f3e0fc8a3cf2bc3ce8e2f2f4add045a"
      define_method(:install) do
        bin.install "junto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swayam-mishra/junto/releases/download/v1.2.0/junto_1.2.0_linux_arm64.tar.gz"
      sha256 "3b8fbd677da8a881ce6b4fd830f99cfa823d413395fa0c4872af5f49b82d3611"
      define_method(:install) do
        bin.install "junto"
      end
    end
  end

  def caveats
    <<~EOS
      Host a watch party:   junto create movie.mkv
      Join one:             junto join <roomcode>
    EOS
  end

  test do
    assert_match "junto", shell_output("#{bin}/junto version")
  end
end
