# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Junto < Formula
  desc "Watch media in sync with friends — no server, no account"
  homepage "https://github.com/swayam-mishra/junto"
  version "1.1.0"
  license "MIT"

  depends_on "mpv"

  on_macos do
    url "https://github.com/swayam-mishra/junto/releases/download/v1.1.0/junto_1.1.0_darwin_all.tar.gz"
    sha256 "017a6343720eb9009a29428deda529b3931764a6c5721999f04e2f374b0d164b"

    define_method(:install) do
      bin.install "junto"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swayam-mishra/junto/releases/download/v1.1.0/junto_1.1.0_linux_amd64.tar.gz"
      sha256 "fa178824986fd17f3de6354f20fc61a183fafb6669244abde1d904a9b3038cbc"
      define_method(:install) do
        bin.install "junto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swayam-mishra/junto/releases/download/v1.1.0/junto_1.1.0_linux_arm64.tar.gz"
      sha256 "e54f565b053bffcd5b666a36827346120969f09c470e12d91eebb439f813075d"
      define_method(:install) do
        bin.install "junto"
      end
    end
  end

  def caveats
    <<~EOS
      Host a watch party:   junto create movie.mkv
      Join one:             junto join <roomcode>
    EOS
  end

  test do
    assert_match "junto", shell_output("#{bin}/junto version")
  end
end
