# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Junto < Formula
  desc "Watch media in sync with friends — no server, no account"
  homepage "https://github.com/swayam-mishra/junto"
  version "1.0.0"
  license "MIT"

  depends_on "mpv"

  on_macos do
    url "https://github.com/swayam-mishra/junto/releases/download/v1.0.0/junto_1.0.0_darwin_all.tar.gz"
    sha256 "f11b70bdd2cf6e6b360b466c4486b6426f38dcaa39d9eeb2aaf73ad847c0196f"

    define_method(:install) do
      bin.install "junto"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/swayam-mishra/junto/releases/download/v1.0.0/junto_1.0.0_linux_amd64.tar.gz"
      sha256 "809fbf3cb2c5f84f02910a7a624a3410eb41d93175cc830739fa5251955c565c"
      define_method(:install) do
        bin.install "junto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/swayam-mishra/junto/releases/download/v1.0.0/junto_1.0.0_linux_arm64.tar.gz"
      sha256 "403f518b3d56a9f7b08b5cf4ade2d846fe5a1e38e886365300ef98bd4417c154"
      define_method(:install) do
        bin.install "junto"
      end
    end
  end

  def caveats
    <<~EOS
      Host a watch party:   junto create movie.mkv
      Join one:             junto join <roomcode>
    EOS
  end

  test do
    assert_match "junto", shell_output("#{bin}/junto version")
  end
end
